repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
    - id: isort
      files: (\.py|julia-t)$
      types: []
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
      files: (\.py|julia-t)$
      types: []
    # See:
    # * https://black.readthedocs.io/en/stable/version_control_integration.html
    # * https://github.com/psf/black/blob/master/.pre-commit-hooks.yaml
