#!/bin/bash

# Usage
#
#    [JULIA_T_JULIA=julia] julia-t [ARGUMENTS...]
#
# Use `julia-t` in place of `julia` to run `julia` with appropriate
# `$JULIA_NUM_THREADS`.  Set environment variable `JULIA_T_JULIA` to
# change the `julia` binary to be used.

# Copyright (c) 2020 Takafumi Arakaki <aka.tkf@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

if [ -z "$JULIA_NUM_THREADS" ]
then
    # Get numebr of physical cores:
    JULIA_NUM_THREADS="$(
        lscpu --parse | \
            grep --invert-match '^#' | \
            sort --unique --field-separator=, --key=2 | \
            wc -l
    )"
fi
export JULIA_NUM_THREADS

JULIA_T_JULIA="${JULIA_T_JULIA:-julia}"
exec "${JULIA_T_JULIA}" "$@"
